#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GenerateDataFormItemsForDictionary.Resource", IsApplication=true)]

namespace GenerateDataFormItemsForDictionary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Android.DataForm.Resource.Attribute.allowNull = global::GenerateDataFormItemsForDictionary.Resource.Attribute.allowNull;
			global::Syncfusion.Android.DataForm.Resource.Attribute.borderColor = global::GenerateDataFormItemsForDictionary.Resource.Attribute.borderColor;
			global::Syncfusion.Android.DataForm.Resource.Attribute.columnCount = global::GenerateDataFormItemsForDictionary.Resource.Attribute.columnCount;
			global::Syncfusion.Android.DataForm.Resource.Attribute.commitMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.commitMode;
			global::Syncfusion.Android.DataForm.Resource.Attribute.culture = global::GenerateDataFormItemsForDictionary.Resource.Attribute.culture;
			global::Syncfusion.Android.DataForm.Resource.Attribute.dataFormValidationMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.dataFormValidationMode;
			global::Syncfusion.Android.DataForm.Resource.Attribute.editorWidth = global::GenerateDataFormItemsForDictionary.Resource.Attribute.editorWidth;
			global::Syncfusion.Android.DataForm.Resource.Attribute.enableGroupSeparator = global::GenerateDataFormItemsForDictionary.Resource.Attribute.enableGroupSeparator;
			global::Syncfusion.Android.DataForm.Resource.Attribute.fontSize = global::GenerateDataFormItemsForDictionary.Resource.Attribute.fontSize;
			global::Syncfusion.Android.DataForm.Resource.Attribute.isReadOnly = global::GenerateDataFormItemsForDictionary.Resource.Attribute.isReadOnly;
			global::Syncfusion.Android.DataForm.Resource.Attribute.labelPosition = global::GenerateDataFormItemsForDictionary.Resource.Attribute.labelPosition;
			global::Syncfusion.Android.DataForm.Resource.Attribute.labelWidth = global::GenerateDataFormItemsForDictionary.Resource.Attribute.labelWidth;
			global::Syncfusion.Android.DataForm.Resource.Attribute.maximumDecimalDigits = global::GenerateDataFormItemsForDictionary.Resource.Attribute.maximumDecimalDigits;
			global::Syncfusion.Android.DataForm.Resource.Attribute.numberFormat = global::GenerateDataFormItemsForDictionary.Resource.Attribute.numberFormat;
			global::Syncfusion.Android.DataForm.Resource.Attribute.numericTextBoxValue = global::GenerateDataFormItemsForDictionary.Resource.Attribute.numericTextBoxValue;
			global::Syncfusion.Android.DataForm.Resource.Attribute.parsingMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.parsingMode;
			global::Syncfusion.Android.DataForm.Resource.Attribute.percentDisplayMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.percentDisplayMode;
			global::Syncfusion.Android.DataForm.Resource.Attribute.selectAllOnFocus = global::GenerateDataFormItemsForDictionary.Resource.Attribute.selectAllOnFocus;
			global::Syncfusion.Android.DataForm.Resource.Attribute.valueChangeMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.valueChangeMode;
			global::Syncfusion.Android.DataForm.Resource.Attribute.watermark = global::GenerateDataFormItemsForDictionary.Resource.Attribute.watermark;
			global::Syncfusion.Android.DataForm.Resource.Attribute.watermarkColor = global::GenerateDataFormItemsForDictionary.Resource.Attribute.watermarkColor;
			global::Syncfusion.Android.DataForm.Resource.Drawable.GroupCollapse = global::GenerateDataFormItemsForDictionary.Resource.Drawable.GroupCollapse;
			global::Syncfusion.Android.DataForm.Resource.Drawable.GroupExpander = global::GenerateDataFormItemsForDictionary.Resource.Drawable.GroupExpander;
			global::Syncfusion.Android.DataForm.Resource.Id.compute = global::GenerateDataFormItemsForDictionary.Resource.Id.compute;
			global::Syncfusion.Android.DataForm.Resource.Id.decimalMode = global::GenerateDataFormItemsForDictionary.Resource.Id.decimalMode;
			global::Syncfusion.Android.DataForm.Resource.Id.doubleMode = global::GenerateDataFormItemsForDictionary.Resource.Id.doubleMode;
			global::Syncfusion.Android.DataForm.Resource.Id.@explicit = global::GenerateDataFormItemsForDictionary.Resource.Id.@explicit;
			global::Syncfusion.Android.DataForm.Resource.Id.left = global::GenerateDataFormItemsForDictionary.Resource.Id.left;
			global::Syncfusion.Android.DataForm.Resource.Id.lostFocus = global::GenerateDataFormItemsForDictionary.Resource.Id.lostFocus;
			global::Syncfusion.Android.DataForm.Resource.Id.onKeyFocus = global::GenerateDataFormItemsForDictionary.Resource.Id.onKeyFocus;
			global::Syncfusion.Android.DataForm.Resource.Id.onLostFocus = global::GenerateDataFormItemsForDictionary.Resource.Id.onLostFocus;
			global::Syncfusion.Android.DataForm.Resource.Id.propertyChanged = global::GenerateDataFormItemsForDictionary.Resource.Id.propertyChanged;
			global::Syncfusion.Android.DataForm.Resource.Id.top = global::GenerateDataFormItemsForDictionary.Resource.Id.top;
			global::Syncfusion.Android.DataForm.Resource.Id.value = global::GenerateDataFormItemsForDictionary.Resource.Id.value;
			global::Syncfusion.Android.DataForm.Resource.Layout.Spinner_item = global::GenerateDataFormItemsForDictionary.Resource.Layout.Spinner_item;
			global::Syncfusion.Android.DataForm.Resource.String.ApplicationName = global::GenerateDataFormItemsForDictionary.Resource.String.ApplicationName;
			global::Syncfusion.Android.DataForm.Resource.String.Hello = global::GenerateDataFormItemsForDictionary.Resource.String.Hello;
			global::Syncfusion.Android.DataForm.Resource.String.library_name = global::GenerateDataFormItemsForDictionary.Resource.String.library_name;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_columnCount = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_columnCount;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_commitMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_commitMode;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_dataFormValidationMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_dataFormValidationMode;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_editorWidth = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_editorWidth;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_isReadOnly = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_isReadOnly;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_labelPosition = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_labelPosition;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfDataForm_labelWidth = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfDataForm_labelWidth;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_allowNull = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_borderColor = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_culture = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_culture;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_fontSize = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_numberFormat = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_parsingMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_watermark = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_watermark;
			global::Syncfusion.Android.DataForm.Resource.Styleable.SfNumericTextBox_watermarkColor = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.allowNull = global::GenerateDataFormItemsForDictionary.Resource.Attribute.allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.borderColor = global::GenerateDataFormItemsForDictionary.Resource.Attribute.borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.culture = global::GenerateDataFormItemsForDictionary.Resource.Attribute.culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.enableGroupSeparator = global::GenerateDataFormItemsForDictionary.Resource.Attribute.enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.fontSize = global::GenerateDataFormItemsForDictionary.Resource.Attribute.fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.maximumDecimalDigits = global::GenerateDataFormItemsForDictionary.Resource.Attribute.maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numberFormat = global::GenerateDataFormItemsForDictionary.Resource.Attribute.numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numericTextBoxValue = global::GenerateDataFormItemsForDictionary.Resource.Attribute.numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.parsingMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.percentDisplayMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.selectAllOnFocus = global::GenerateDataFormItemsForDictionary.Resource.Attribute.selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.valueChangeMode = global::GenerateDataFormItemsForDictionary.Resource.Attribute.valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermark = global::GenerateDataFormItemsForDictionary.Resource.Attribute.watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermarkColor = global::GenerateDataFormItemsForDictionary.Resource.Attribute.watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.compute = global::GenerateDataFormItemsForDictionary.Resource.Id.compute;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.decimalMode = global::GenerateDataFormItemsForDictionary.Resource.Id.decimalMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.doubleMode = global::GenerateDataFormItemsForDictionary.Resource.Id.doubleMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onKeyFocus = global::GenerateDataFormItemsForDictionary.Resource.Id.onKeyFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onLostFocus = global::GenerateDataFormItemsForDictionary.Resource.Id.onLostFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.value = global::GenerateDataFormItemsForDictionary.Resource.Id.value;
			global::Com.Syncfusion.Numerictextbox.Resource.String.library_name = global::GenerateDataFormItemsForDictionary.Resource.String.library_name;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_allowNull = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_borderColor = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_culture = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_fontSize = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numberFormat = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_parsingMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermark = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermarkColor = global::GenerateDataFormItemsForDictionary.Resource.Styleable.SfNumericTextBox_watermarkColor;
			global::Com.Syncfusion.Numericupdown.Resource.String.library_name = global::GenerateDataFormItemsForDictionary.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int allowNull = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int borderColor = 2130771978;
			
			// aapt resource value: 0x7f010013
			public const int columnCount = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int commitMode = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int culture = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int dataFormValidationMode = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int editorWidth = 2130771986;
			
			// aapt resource value: 0x7f010003
			public const int enableGroupSeparator = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int fontSize = 2130771976;
			
			// aapt resource value: 0x7f010014
			public const int isReadOnly = 2130771988;
			
			// aapt resource value: 0x7f010010
			public const int labelPosition = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int labelWidth = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int maximumDecimalDigits = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int numberFormat = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int numericTextBoxValue = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int parsingMode = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int percentDisplayMode = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int selectAllOnFocus = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int valueChangeMode = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int watermark = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int watermarkColor = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int GroupCollapse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GroupExpander = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int compute = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int decimalMode = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int doubleMode = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int @explicit = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int left = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int lostFocus = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int onKeyFocus = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int onLostFocus = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int propertyChanged = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int top = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int value = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Spinner_item = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SfDataForm = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 5
			public const int SfDataForm_columnCount = 5;
			
			// aapt resource value: 1
			public const int SfDataForm_commitMode = 1;
			
			// aapt resource value: 0
			public const int SfDataForm_dataFormValidationMode = 0;
			
			// aapt resource value: 4
			public const int SfDataForm_editorWidth = 4;
			
			// aapt resource value: 6
			public const int SfDataForm_isReadOnly = 6;
			
			// aapt resource value: 2
			public const int SfDataForm_labelPosition = 2;
			
			// aapt resource value: 3
			public const int SfDataForm_labelWidth = 3;
			
			public static int[] SfNumericTextBox = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 9
			public const int SfNumericTextBox_allowNull = 9;
			
			// aapt resource value: 10
			public const int SfNumericTextBox_borderColor = 10;
			
			// aapt resource value: 12
			public const int SfNumericTextBox_culture = 12;
			
			// aapt resource value: 3
			public const int SfNumericTextBox_enableGroupSeparator = 3;
			
			// aapt resource value: 8
			public const int SfNumericTextBox_fontSize = 8;
			
			// aapt resource value: 6
			public const int SfNumericTextBox_maximumDecimalDigits = 6;
			
			// aapt resource value: 4
			public const int SfNumericTextBox_numberFormat = 4;
			
			// aapt resource value: 13
			public const int SfNumericTextBox_numericTextBoxValue = 13;
			
			// aapt resource value: 0
			public const int SfNumericTextBox_parsingMode = 0;
			
			// aapt resource value: 1
			public const int SfNumericTextBox_percentDisplayMode = 1;
			
			// aapt resource value: 7
			public const int SfNumericTextBox_selectAllOnFocus = 7;
			
			// aapt resource value: 2
			public const int SfNumericTextBox_valueChangeMode = 2;
			
			// aapt resource value: 5
			public const int SfNumericTextBox_watermark = 5;
			
			// aapt resource value: 11
			public const int SfNumericTextBox_watermarkColor = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
